class DummmyData {
  static const orders = [
    {
      "from": "Durgapur, West Bengal",
      "to": "Barpeta, Assam",
      "startdate": "08-Mar-2023",
      "endDate": "To be determined",
      "tone": "30",
      "status": "Pending",
    },
    {
      "from": "Kolkata, West Bengal",
      "to": "Nikaram, Hyderbad",
      "startdate": "09-Jun-2023",
      "endDate": "09-Sep-2023",
      "tone": "40",
      "status": "In-Process",
    },
    {
      "from": "Drounk, Andra Pradesh",
      "to": "Hatia, Mizorum",
      "startdate": "18-Mar-2023",
      "endDate": "To be determined",
      "tone": "35",
      "status": "Pending",
    },
    {
      "from": "Kolkata, West Bengal",
      "to": "Nikaram, Hyderbad",
      "startdate": "09-Jun-2023",
      "endDate": "09-Sep-2023",
      "tone": "40",
      "status": "In-Process",
    },
    {
      "from": "Drounk, Andra Pradesh",
      "to": "Hatia, Mizorum",
      "startdate": "18-Mar-2023",
      "endDate": "To be determined",
      "tone": "35",
      "status": "Pending",
    },
    {
      "from": "Kolkata, West Bengal",
      "to": "Nikaram, Hyderbad",
      "startdate": "09-Jun-2023",
      "endDate": "09-Sep-2023",
      "tone": "40",
      "status": "In-Process",
    },
    {
      "from": "Drounk, Andra Pradesh",
      "to": "Hatia, Mizorum",
      "startdate": "18-Mar-2023",
      "endDate": "To be determined",
      "tone": "35",
      "status": "Pending",
    },
    {
      "from": "Drounk, Andra Pradesh",
      "to": "Hatia, Mizorum",
      "startdate": "18-Mar-2023",
      "endDate": "To be determined",
      "tone": "35",
      "status": "Pending",
    },
    {
      "from": "Drounk, Andra Pradesh",
      "to": "Hatia, Mizorum",
      "startdate": "18-Mar-2023",
      "endDate": "To be determined",
      "tone": "35",
      "status": "Pending",
    },
    {
      "from": "Drounk, Andra Pradesh",
      "to": "Hatia, Mizorum",
      "startdate": "18-Mar-2023",
      "endDate": "To be determined",
      "tone": "35",
      "status": "Pending",
    },
    {
      "from": "Drounk, Andra Pradesh",
      "to": "Hatia, Mizorum",
      "startdate": "18-Mar-2023",
      "endDate": "To be determined",
      "tone": "35",
      "status": "Pending",
    },
    {
      "from": "Drounk, Andra Pradesh",
      "to": "Hatia, Mizorum",
      "startdate": "18-Mar-2023",
      "endDate": "To be determined",
      "tone": "35",
      "status": "Pending",
    },
    {
      "from": "Drounk, Andra Pradesh",
      "to": "Hatia, Mizorum",
      "startdate": "18-Mar-2023",
      "endDate": "To be determined",
      "tone": "35",
      "status": "Pending",
    },
    {
      "from": "Drounk, Andra Pradesh",
      "to": "Hatia, Mizorum",
      "startdate": "18-Mar-2023",
      "endDate": "To be determined",
      "tone": "35",
      "status": "Pending",
    },
  ];
}
